---
# tasks file for roles/webserver
- name: Spinning up my webserver 
  amazon.aws.ec2_instance:
    vpc_subnet_id: "{{ public_subnet.subnet.id }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    security_group: "{{ myVPCSecurityGroup.group_id }}"
    name: myVPCServer
    network:
      assign_public_ip: true
    state: present
    wait: true
    tags:
      EnvName: Test-Environment
  register: ec2
  delegate_to: localhost

- name: Add instance to the host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action:
    module: wait_for
    host: "{{ item.public_ip }}"
    port: 22
    delay: 10
    timeout: 120
  loop: "{{ ec2.instances }}"