---
# tasks file for roles/vpc
- name: Create the AWS VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ region }}"
    state: present
  register: vpc_result
  
- name: Create Subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_result.vpc.id }}"
    cidr: 10.100.0.0/24
    az: "{{ region }}a"
    region: "{{ region }}"
    state: present
    tags:
      Name: myVPC-Subnet
  register: subnet
  
  
- name: Create Internet Gateway
  community.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc_result.vpc.id }}"
    region: "{{ region }}"
  register: igw

- name: Create Route Table
  amazon.aws.ec2_vpc_route_table:
    subnets:
      - "{{ subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    vpc_id: "{{ vpc_result.vpc.id }}"
    tags:
      Name: myVPCRouteTable

