---
# tasks file for roles/sg
- name: My Instance Security Group
  amazon.aws.ec2_group:
    name: myVPCSecurityGroup
    description: Security group with SSH capabilities
    vpc_id: "{{ vpc_result.vpc.id }}"
    rules:
      - proto: tcp
        ports:
         - '22'
         - '80'
         - '443'
        cidr_ip: 0.0.0.0/0
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 73.82.230.253/32
  register: myVPCSecurityGroup      
  