---
# tasks file for roles/deployment
- name: Ensure apache is installed
  become: yes
  yum:
    name: httpd
    state: present

- name: Starting Apache
  become: yes
  service:
    name: httpd
    state: started
    enabled: true

- name: Generating Template
  become: yes
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restarting my Linux
 