---
# tasks file for roles/vpc
- name: Create the AWS VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ region }}"
    state: present
  register: vpc_result
  
- name: Create Public Subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_result.vpc.id }}"
    cidr: 10.100.0.0/24
    az: "{{ region }}a"
    region: "{{ region }}"
    state: present
    tags:
      Name: myVPC-Public-Subnet
  register: public_subnet

- name: Create Private Subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_result.vpc.id }}"
    cidr: 10.100.1.0/24
    az: "{{ region }}a"
    region: "{{ region }}"
    state: present
    tags:
      Name: myVPC-Private-Subnet
  register: private_subnet

- name: Create new nat gateway and allocate new EIP if a nat gateway does not yet exist in the subnet.
  amazon.aws.ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ public_subnet.subnet.id }}"
    wait: true
    region: "{{ region }}"
    if_exist_do_not_create: true
  register: new_nat_gateway
  
  
- name: Create Internet Gateway
  community.aws.ec2_vpc_igw:
    vpc_id: "{{ vpc_result.vpc.id }}"
    region: "{{ region }}"
    state: present
  register: igw

- name: Create Public Route Table
  amazon.aws.ec2_vpc_route_table:
    subnets:
      - "{{ public_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    vpc_id: "{{ vpc_result.vpc.id }}"
    tags:
      Name: myVPCRouteTable

- name: Create Private Route Table
  amazon.aws.ec2_vpc_route_table:
    subnets:
      - "{{ private_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
    vpc_id: "{{ vpc_result.vpc.id }}"
    tags:
      Name: myVPCRouteTable
