---
# create_vpc.yml
- name: Create VPC, SG and Webserver using the localhost
  hosts: localhost
  gather_facts: no
  roles:
    - vpc
    - sg
    - webserver

- name: Do deployment activities on the hosts
  hosts: localhost
  roles:
    - deployment