---
# create_vpc.yml
- name: Create VPC, SG and Webserver using the localhost
  hosts: localhost
  gather_facts: no
  roles:
    - create-vpc
    - create-public-subnet
    - create-private-subnet
    - create-igw
    - create-public-rt
    - create-nat-gtw
    - create-private-rt
    - create-sg
    - create-instance

- name: Do deployment activities on the hosts
  hosts: ubuntu
  gather_facts: no
  roles:
    - ssh_key_copy
  tasks:
    - name: ping the dynamic host
      ping:

