---
# tasks file for ansibleproject/roles/create-public-subnet
- name: Create Public Subnet
  amazon.aws.ec2_vpc_subnet:
    vpc_id: "{{ vpc_result.vpc.id }}"
    cidr: "{{ public_}}"
    az: "{{ region }}a"
    region: "{{ region }}"
    state: present
    tags:
      Name: myVPC-Public-Subnet
  register: public_subnet
