---
# tasks file for roles/deployment
- name: Ensure apache is installed
  become: true
  package:
    name: httpd
    state: present
  register: httpd
  
- name: Starting Apache
  become: true
  service:
    name: httpd
    state: started
    enabled: true

- name: Generating Template
  become: true
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
 
 