---
# tasks file for roles/sg
- name: My Instance Security Group
  amazon.aws.ec2_group:
    name: myVPCSecurityGroup
    description: Security group with SSH capabilities
    vpc_id: "{{ vpc_result.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
  register: myVPCSecurityGroup      
  