---
# tasks file for roles/webserver
- name: Spinning up my webserver 
  amazon.aws.ec2_instance:
    vpc_subnet_id: "{{ public_subnet.subnet.id }}"
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    instance_type: "{{ instance_type }}"
    image_id: "{{ image_id }}"
    security_group: "{{ myVPCSecurityGroup.group_id }}"
    name: myVPCServer
    network:
      assign_public_ip: true
    state: present
    wait: true
    tags:
      EnvName: Test-Environment
  async: 3600
  poll: 0
  register: ec2_result

- name: Wait for the EC2 instance to finish provisioning
  async_status:
    jid: "{{ ec2_result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100  # Set the number of retries as needed
  delay: 10    # Set the delay between retries (in seconds)