---
# tasks file for ansibleproject/roles/create-nat-gtw
- name: Create new nat gateway and allocate new EIP if a nat gateway does not yet exist in the subnet.
  amazon.aws.ec2_vpc_nat_gateway:
    state: present
    subnet_id: "{{ public_subnet.subnet.id }}"
    wait: true
    region: "{{ region }}"
    if_exist_do_not_create: true
  register: new_nat_gateway