---
# tasks file for delete-instance
- name: Deleting the Instance
  amazon.aws.ec2_instance:
    region: "{{ region }}"
    state: absent
    filters:
      instance-state-name: running
      tag:Name : "{{ ec2_name_tag }}"
      tag:EnvName : "{{ ec2_env }}"

- name: Grab VPC details
  amazon.aws.ec2_vpc_net_info:
    region: "{{ region }}"
  register: all_vpcs

- name: Gather information about NAT gateways
  amazon.aws.ec2_vpc_nat_gateway_info:
    region: "{{ region }}"
    filters:
      state: ['available']
  register: nat_gateway_result

# - name: Delete nat gateway and release EIP.
#   community.aws.ec2_vpc_nat_gateway:
#     state: absent
#     nat_gateway_id: "{{ nat_gateway_result.result[0].nat_gateway_id }}"
#     release_eip: true
#     wait: yes
#     wait_timeout: 300
#     region: "{{ region }}"

- name: Gather all route tables
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ all_vpcs.id }}"
    region: "{{ region }}"
  register: route_tables

- name: Delete Route Tables
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ all_vpcs.vpcs.id }}"
    region: "{{ region }}"
    route_table_id: "{{ route_tables.route_tables }}"
    state: absent

- name: Remove subnet for servers
  amazon.aws.ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ all_vpcs.id }}"
    

#- name: Delete Public Subnet
- name: Delete AWS VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ region }}"
    state: absent
   